### ISSUE TITLE
Add tagging on images for registration

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/dashQC_fmri#10]
When users review the coregistration they should be able to click on the brain to indicate where they think something went wrong.

Something like this:
![image.png](https://images.zenhubusercontent.com/59b5bc47b0222d5de47723c9/0fcd8333-d4e5-4738-b9ca-3e83702fca92)

**Comment by jarmoza** [comment]
Added in 5a45b9cd5fc02b0dc08a46389e959d703a474a1a
