### ISSUE TITLE
The 'Save QC' button does not download a json file in both firefox and chrome.  

### ISSUE THREAD

**Issue by HanadS** [SIMEXP/dashQC_fmri#42]

**Comment by jarmoza** [comment]
@HanadS Can you attach a screenshot of the browser debugger? I was not experiencing this issue in my last commit on either Firefox or Chrome.

**Comment by HanadS** [comment]
Hi @jarmoza , there's no error in the browser debugger. There's only this warning. 

```The script from “https://api.keen.io/3.0/projects/5368fa5436bf5a5623000000/ev…&modified=1563552019373&jsonp=keenJSONPCallback1563552019373” was loaded even though its MIME type (“application/json”) is not a valid JavaScript MIME type.```

**Comment by jarmoza** [comment]
Fixed in 888cb72cb4a8629234285312121c13094a45a70d
