### ISSUE TITLE
bold/T1 registration is broken in the demo

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/dashQC_fmri#45]
putting the mouse on top of the image does not trigger the shift to the T1

**Comment by jarmoza** [comment]
That's correct. The behavior has been changed so that the image between the template and subject continuously shift. Mouseover now freezes the image transition so users can view and click areas in the image where they feel there may be issues.

**Comment by HanadS** [comment]
Hi @jarmoza I'm still seeing this issue. There are no transitions between bold and T1 in the latest version of the dashboard

**Comment by jarmoza** [comment]
I had misread the initial issue. Bold v T1 image animation/hover is now fixed in https://github.com/SIMEXP/dashQC_fmri/commit/ff3d59bd0917db1fca7ac1695b90b601a1f457be

**Comment by pbellec** [comment]
Thanks a lot Jonathan!
