### ISSUE TITLE
loadQC does not work for Firefox and Chrome

### ISSUE THREAD

**Issue by HanadS** [SIMEXP/dashQC_fmri#7]
Error: importSubjectInfo is not defined qc_dash_objects.js:860

**Comment by jarmoza** [comment]
Suggested web app: https://crossbrowsertesting.com/

**Comment by jarmoza** [comment]
Fixed in 7504ab4d7611ab41e3b3476cba6f3887050d6f48

**Comment by jarmoza** [comment]
@HanadS can you confirm and close?
